/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/learn`; params?: Router.UnknownInputParams; } | { pathname: `/learn-check`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/study-session` | `/study-session`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progress` | `/progress`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/age`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/diagnostic`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal-selection`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/knowledge-map-reveal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/proficiency-assessment`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/quiz`; params?: Router.UnknownOutputParams; } | { pathname: `/learn`; params?: Router.UnknownOutputParams; } | { pathname: `/learn-check`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/study-session` | `/study-session`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/progress` | `/progress`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/age`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/diagnostic`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goal-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/knowledge-map-reveal`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/proficiency-assessment`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/quiz${`?${string}` | `#${string}` | ''}` | `/learn${`?${string}` | `#${string}` | ''}` | `/learn-check${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/study-session${`?${string}` | `#${string}` | ''}` | `/study-session${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/progress${`?${string}` | `#${string}` | ''}` | `/progress${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/verify${`?${string}` | `#${string}` | ''}` | `/onboarding/age${`?${string}` | `#${string}` | ''}` | `/onboarding/diagnostic${`?${string}` | `#${string}` | ''}` | `/onboarding/goal-selection${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/knowledge-map-reveal${`?${string}` | `#${string}` | ''}` | `/onboarding/paywall${`?${string}` | `#${string}` | ''}` | `/onboarding/proficiency-assessment${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/quiz`; params?: Router.UnknownInputParams; } | { pathname: `/learn`; params?: Router.UnknownInputParams; } | { pathname: `/learn-check`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/study-session` | `/study-session`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progress` | `/progress`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/age`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/diagnostic`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goal-selection`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/knowledge-map-reveal`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/proficiency-assessment`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
